# Generated by Django 5.2.12 on 2026-04-01 18:43

import apps.core.utils
import apps.machines.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('dealers', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено в')),
                ('name', models.CharField(max_length=255, verbose_name='Название машины')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('serial_number', models.CharField(max_length=128, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, max_length=64, verbose_name='Инвентарный номер')),
                ('category', models.CharField(choices=[('excavator', 'Экскаватор'), ('loader', 'Погрузчик'), ('crane', 'Кран'), ('dozer', 'Бульдозер'), ('grader', 'Автогрейдер'), ('other', 'Другое')], default='other', max_length=24, verbose_name='Категория')),
                ('status', models.CharField(choices=[('active', 'В эксплуатации'), ('service', 'На сервисе'), ('inactive', 'Неактивна'), ('decommissioned', 'Выведена из эксплуатации')], db_index=True, default='active', max_length=24, verbose_name='Статус')),
                ('photo', models.ImageField(blank=True, upload_to=apps.machines.models.machine_photo_upload_to, verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('emergency_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Экстренный телефон')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='Публично доступна')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('operating_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Наработка, моточасы')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего обслуживания')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего обслуживания')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='branches.branch', verbose_name='Филиал')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='dealers.dealer', verbose_name='Дилер')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Организация')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='branches.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ('organization__name', 'name', 'serial_number'),
            },
        ),
        migrations.CreateModel(
            name='MachineTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено в')),
                ('tag_type', models.CharField(choices=[('nfc', 'NFC'), ('qr', 'QR'), ('hybrid', 'NFC + QR')], default='hybrid', max_length=16, verbose_name='Тип тега')),
                ('public_token', models.CharField(db_index=True, default=apps.core.utils.generate_public_token, help_text='Используется в публичном URL и не должен совпадать с внутренними ID.', max_length=48, unique=True, verbose_name='Публичный токен')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('issued_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата выдачи')),
                ('replaced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата замены')),
                ('replacement_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина замены')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='machines.machine', verbose_name='Машина')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Организация')),
                ('previous_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='machines.machinetag', verbose_name='Предыдущий тег')),
            ],
            options={
                'verbose_name': 'Тег машины',
                'verbose_name_plural': 'Теги машин',
                'ordering': ('-issued_at', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['organization', 'status'], name='machines_ma_organiz_d87045_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['organization', 'next_maintenance_date'], name='machines_ma_organiz_519d2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'serial_number'), name='uniq_machine_serial_per_org_active'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('inventory_number', ''), _negated=True)), fields=('organization', 'inventory_number'), name='uniq_machine_inventory_per_org_active'),
        ),
        migrations.AddConstraint(
            model_name='machinetag',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('machine',), name='uniq_active_tag_per_machine'),
        ),
    ]
