# Generated by Django 5.2.12 on 2026-04-01 18:43

import apps.attachments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено в')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='ID объекта')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to=apps.attachments.models.attachment_upload_to, verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('pdf', 'PDF'), ('document', 'Документ'), ('spreadsheet', 'Таблица'), ('archive', 'Архив'), ('other', 'Другое')], default='other', max_length=16, verbose_name='Тип файла')),
                ('visibility', models.CharField(choices=[('public', 'Публичный'), ('internal', 'Внутренний')], db_index=True, default='internal', max_length=16, verbose_name='Видимость')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя файла')),
                ('mime_type', models.CharField(blank=True, max_length=128, verbose_name='MIME-тип')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Размер, байт')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Организация')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='attachments_content_44d952_idx'), models.Index(fields=['organization', 'visibility'], name='attachments_organiz_4a3016_idx')],
            },
        ),
    ]
