# Generated by Django 5.2.12 on 2026-04-01 18:43

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('dealers', '0001_initial'),
        ('machines', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено в')),
                ('source', models.CharField(choices=[('public_page', 'Публичная страница'), ('manual', 'Ручное создание'), ('phone', 'Телефон'), ('internal', 'Внутренний канал')], db_index=True, default='manual', max_length=16, verbose_name='Источник')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон клиента')),
                ('client_company', models.CharField(blank=True, max_length=255, verbose_name='Компания клиента')),
                ('problem_description', models.TextField(verbose_name='Описание проблемы')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('triaged', 'Квалифицирована'), ('scheduled', 'Запланирована'), ('in_progress', 'В работе'), ('waiting_parts', 'Ожидание запчастей'), ('completed', 'Выполнена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], db_index=True, default='new', max_length=24, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критический')], db_index=True, default='normal', max_length=16, verbose_name='Приоритет')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок реакции')),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='Первый ответ')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решено')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыто')),
                ('consent_to_processing', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
                ('routing_applied', models.BooleanField(default=False, verbose_name='Маршрутизация применена')),
                ('internal_note', models.TextField(blank=True, verbose_name='Внутренняя заметка')),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный инженер')),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='branches.branch', verbose_name='Филиал')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='dealers.dealer', verbose_name='Дилер')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='machines.machine', verbose_name='Машина')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Организация')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='branches.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Сервисная заявка',
                'verbose_name_plural': 'Сервисные заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено в')),
                ('service_date', models.DateField(verbose_name='Дата обслуживания')),
                ('work_type', models.CharField(choices=[('preventive', 'Плановое ТО'), ('repair', 'Ремонт'), ('diagnostic', 'Диагностика'), ('warranty', 'Гарантийные работы'), ('inspection', 'Инспекция'), ('commissioning', 'Ввод в эксплуатацию'), ('other', 'Другое')], default='preventive', max_length=24, verbose_name='Тип работ')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('operating_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Наработка, моточасы')),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег, км')),
                ('public_summary', models.TextField(blank=True, verbose_name='Публичное резюме')),
                ('is_public', models.BooleanField(db_index=True, default=False, verbose_name='Показывать публично')),
                ('private_notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Следующая дата обслуживания')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='branches.branch', verbose_name='Филиал')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to=settings.AUTH_USER_MODEL, verbose_name='Инженер')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_records', to='machines.machine', verbose_name='Машина')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Организация')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='service.servicerequest', verbose_name='Связанная заявка')),
            ],
            options={
                'verbose_name': 'Сервисная запись',
                'verbose_name_plural': 'Сервисные записи',
                'ordering': ('-service_date', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['organization', 'status', 'priority'], name='service_ser_organiz_694b56_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['organization', 'region', 'branch'], name='service_ser_organiz_ccb642_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['organization', 'due_at'], name='service_ser_organiz_f15562_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerecord',
            index=models.Index(fields=['organization', 'service_date'], name='service_ser_organiz_1e9cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerecord',
            index=models.Index(fields=['organization', 'is_public'], name='service_ser_organiz_55dc93_idx'),
        ),
    ]
