# Generated by Django 5.2.12 on 2026-04-01 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создание'), ('updated', 'Изменение'), ('deleted', 'Удаление'), ('status_changed', 'Смена статуса'), ('assigned', 'Назначение'), ('login', 'Вход'), ('public_request_created', 'Создание публичной заявки'), ('export', 'Экспорт')], db_index=True, max_length=32, verbose_name='Действие')),
                ('model_name', models.CharField(db_index=True, max_length=128, verbose_name='Модель')),
                ('object_id', models.CharField(db_index=True, max_length=64, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Представление объекта')),
                ('summary', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organization', verbose_name='Организация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ('-timestamp',),
            },
        ),
    ]
