# Generated by Django 5.2.12 on 2026-04-01 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено в')),
                ('warranty_start', models.DateField(verbose_name='Начало гарантии')),
                ('warranty_end', models.DateField(verbose_name='Окончание гарантии')),
                ('warranty_type', models.CharField(choices=[('standard', 'Стандартная'), ('extended', 'Расширенная'), ('powertrain', 'Силовая линия'), ('service_contract', 'Сервисный контракт'), ('other', 'Другое')], default='standard', max_length=24, verbose_name='Тип гарантии')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('expiring', 'Истекает'), ('expired', 'Истекла'), ('void', 'Аннулирована'), ('pending', 'Ожидает начала')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('public_summary', models.CharField(blank=True, max_length=255, verbose_name='Публичное описание')),
                ('notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranties', to='machines.machine', verbose_name='Машина')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Гарантия',
                'verbose_name_plural': 'Гарантии',
                'ordering': ('-warranty_end',),
                'constraints': [models.CheckConstraint(condition=models.Q(('warranty_end__gte', models.F('warranty_start'))), name='warranty_end_after_start')],
            },
        ),
    ]
