# Generated by Django 5.2.12 on 2026-04-01 18:43

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено в')),
                ('name', models.CharField(max_length=255, verbose_name='Название дилера')),
                ('code', models.CharField(max_length=32, verbose_name='Код дилера')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Юридическое название')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон')),
                ('emergency_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Экстренный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('branches', models.ManyToManyField(blank=True, related_name='dealers', to='branches.branch', verbose_name='Филиалы')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Дилер',
                'verbose_name_plural': 'Дилеры',
                'ordering': ('organization__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалено в')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_type', models.CharField(choices=[('service', 'Сервис'), ('emergency', 'Экстренный'), ('manager', 'Менеджер'), ('sales', 'Продажи'), ('operator', 'Оператор'), ('other', 'Другое')], default='service', max_length=24, verbose_name='Тип контакта')),
                ('visibility', models.CharField(choices=[('public', 'Публичный'), ('internal', 'Внутренний')], default='internal', max_length=16, verbose_name='Видимость')),
                ('public_note', models.CharField(blank=True, max_length=255, verbose_name='Публичная заметка')),
                ('private_note', models.TextField(blank=True, verbose_name='Внутренняя заметка')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='branches.branch', verbose_name='Филиал')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Организация')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='dealers.dealer', verbose_name='Дилер')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ('organization__name', 'full_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='dealer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'code'), name='uniq_dealer_code_per_org_active'),
        ),
    ]
